openapi: 3.0.3
info:
  title: Topic API
  version: 0.9.0
paths:
  /api/topic:
    get:
      description: List all topics by Name and ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TopicIdentifiers'
    post:
      description: Create a new Topic
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Topic'
      responses:
        '201':
          $ref: '#/components/responses/Topic'
  /api/topic/{id}:
    get:
      description: Return a Topic by ID
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          $ref: '#/components/responses/Topic'
    patch:
      description: Update a Topic by ID
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          $ref: '#/components/responses/Topic'
  /api/topic/{id}/resource:
    post:
      description: Add a resource to a topic
      parameters:
        - $ref: '#/components/parameters/Id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resource'
      responses:
        '200':
          $ref: '#/components/responses/Topic'
  /api/topic/{id}/resource/{name}:
    patch:
      description: Update a resource on a topic
      parameters:
        - $ref: '#/components/parameters/Id'
        - $ref: '#/components/parameters/Name'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resource'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
    delete:
      description: Remove a resource from a Topic
      parameters:
        - $ref: '#/components/parameters/Id'
        - $ref: '#/components/parameters/Name'
      responses:
        '200':
          description: OK
components:
  responses:
    Topic:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Topic'
  parameters:
    Id:
      name: id
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/TopicIdentifiers/properties/Id'
    Name:
      name: name
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/TopicIdentifiers/properties/Name'
  schemas:
    TopicIdentifiers:
      type: object
      properties:
        Id:
          type: string
        Name:
          type: string
    Topic:
      required:
        - Name
      allOf:
        - $ref: '#/components/schemas/TopicIdentifiers'
        - type: object
          properties:
            Domain:
              type: string
              items:
                $ref: '#/components/schemas/Domain'
            Skills:
              type: array
              items:
                type: string
            Status:
              type: string
              enum:
                - Active
                - Archived
            Overview:
              type: string
            Resources:
              type: array
              items:
                $ref: '#/components/schemas/Resource'
    Resource:
      type: object
      properties:
        Name:
          type: string
        Type:
          type: string
          enum:
            - Article
            - Book
            - Certification Exam
            - Course
            - Design System
            - Document
            - Exercise
            - EngineerKit Resource
            - Film
            - Game
            - Guide
            - Image
            - Official Guide
            - Official Training
            - Resource
            - Tool
            - Thread
            - Tutorial
            - Video
            - Video Series
            - Website
        Duration:
          type: integer
        Description:
          type: string
        Link:
          type: string
        isFree:
          type: boolean
        isGeneralistSkill:
          type: boolean
        Notes:
          type: string
    Domain:
      type: string
      enum:
        - Architecture
        - Automated Testing
        - Clean Code
        - Computing
        - Craftsmanship
        - Data
        - Human Experience
        - Infrastructure
        - Internet
        - Monitoring
        - Operations
        - Product Life Cycle
        - Programming Languages
        - Security
        - Tooling
