openapi: 3.0.3
info:
  title: Topic API
  version: 0.3.0
paths:
  /api/topic:
    get:
      description: List all topics by Name and ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TopicIdentifiers'
components:
  schemas:
    TopicIdentifiers:
      type: object
      properties:
        Id:
          type: string
        Name:
          type: string
    Topic:
      required:
        - Name
      allOf:
        - $ref: '#/components/schemas/TopicIdentifiers'
        - type: object
          properties:
            Domain:
              type: string
              items:
                $ref: '#/components/schemas/Domain'
            Skills:
              type: array
              items:
                type: string
            Status:
              type: string
              enum:
                - Active
                - Archived
            Overview:
              type: string
            Resources:
              type: array
              items:
                $ref: '#/components/schemas/Resource'
    Resource:
      type: object
      properties:
        Name:
          type: string
        Type:
          type: string
          enum:
            - Article
            - Book
            - Certification Exam
            - Course
            - Design System
            - Document
            - Exercise
            - EngineerKit Resource
            - Film
            - Game
            - Guide
            - Image
            - Official Guide
            - Official Training
            - Resource
            - Tool
            - Thread
            - Tutorial
            - Video
            - Video Series
            - Website
        Duration:
          type: integer
        Description:
          type: string
        Link:
          type: string
        isFree:
          type: boolean
        isGeneralistSkill:
          type: boolean
        Notes:
          type: string
    Domain:
      type: string
      enum:
        - Architecture
        - Automated Testing
        - Clean Code
        - Computing
        - Craftsmanship
        - Data
        - Human Experience
        - Infrastructure
        - Internet
        - Monitoring
        - Operations
        - Product Life Cycle
        - Programming Languages
        - Security
        - Tooling
